# .github/workflows/static.yml
name: Deploy static content to Pages

on:
  # Trigger automatically when someone pushes to main
  push:
    branches: ["main"]

  # Allow manual runs from the Actions tab
  workflow_dispatch:

# Grant the GITHUB_TOKEN the exact permissions needed for Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Only one Pages deploy can run at a time (don’t cancel in-progress jobs)
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload site content
        uses: actions/upload-pages-artifact@v1
        with:
          path: "."   # Deploy everything at the repo root (must include index.html)

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
